language: python
python:
- '3.7'
services: postgresql
env:
  global:
  - DATABASE_URL=postgresql://postgres@localhost/travis_ci_test
  - secure: wMAqgPWGoSUexItnI7XHaFoIWBxOoU5QiY7H2T6EgGPEsC2EnMXjXaVrozavH9z8nFEFhjGfj/xHsPFTHNE0qt4KfgZzwhIUWYJvWEjmOR+1U2Nw99cIEAXf/uL9cPZ3qdf8JAOT/SXcNMwoVcxdZKF3zyMUCYbw6BZBdefiPb8QLN9l0P3J+Ajkx79Kpv3PlXdNAappUoPG7BurJ/ucI5fAcNZd2LDj9cTs0tPy8YmXZCxTxrSDdl3O/Q45hWH2Nj1GXgnGcD2TrOhSLrikN+BWmRMOLh7WVAHlM13lcrp0GadS6qw6WL0fdlP/NUARUXFvLEkYzPGbrZfmkTTgnrQUpEF+sCQcByRMlUq7UCrC1cehV8lJ0ej0C11HEZM2x3sv57x9aFJzHjQXy4orFa8wnSq/Vf5nnSPJSXIx1mkSn+ztwRctNzLAHod41zx1D2+tNYMVQUSGI+SAZIKtZ9oOU4nk/YldIE/T3Ynb6tI1/gv34+Rhuu4MQv3noqD0Nd+xZ2TF11snD9J9AAuo3KOt+YgUf6v6EeclidhfHtkQFfHjZXXh7P7yFirPYE7toYRmGPCUA0OGLkIiQeki7l/0qo2R0lzkN/VW9z3iurRQsXiMIkMxiI0lRDjHqGyXXvkODqmlBTGnoWWVuBSZ1vXhqXxlg0CxSKUK0YvXGkQ=
install:
- pip install -r requirements.txt
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
script:
- python -m unittest discover
deploy:
  provider: heroku
  api_key:
    secure: CBr/9CR0eiggiQ1YS2PoqHrL0wTYh/r4yA7PZIKFhaOh/lzccH4uhcyzHI9UCmND+nFSWYeWjZucHgVSizGNwTh080/CSVM5Cty5w6BlQihT9CHLsjGxF6LmkAaINF+5TOpuQtSk5PT4MeFtFrAbAbMOgATBZuF3QWW/csOfVUOAsiy2n4W1LcKCtEhidqCze2VUwqW5reXNTeOVd1gqxseAD1HE47yN6CqPLs8Z92iqDdSD+kNwUrh8pYT908QIlk0iQAoomdnAoNETdBLYXNPi4uGYyipzPBEGU0QRgd/akgdRJJzpTOPSQia5gjRiDPxrm/PvSKJU++codKv0CEBnNG+m4AcwtzQz44cWj9nYMo/oAzJ+FqZb8lwfqFkzEikpA+x98n88y4gO/Qr5EfRQ4hHatkJEjpftdO6GeNeq0f5qjTQRNDm3ezZWNnRyWW3DItS5hJ0xY5mpVsXymYrwljAJpBCGCJvybFFI0YMiHQb+JVqd+Tw0Vsznq8PwlfgnMKtsew0zKJ0EDJITqT/74fu/Rh35+mK7jPhMTiynKgXq1TUD/h0bajU9F5gxm1twgtiFfYqNNg8qFL61USvbl+tclOIkHv1E4Y3fxaEtXwKrJy/oGppbJCapypWTzAwYSYiZ2PqIJuK4edLCXnVX+k6TfTT2MfAAMfNNcgo=
  app: extract-feed-bot
  on:
    repo: Yunato/extract-feed-bot
